name: bus_saathi
description: ਬੱਸ ਸਾਥੀ - Offline Punjabi Bus Tracker
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  http: ^1.5.0
  vector_math: ^2.1.4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/data/
    - assets/map_tiles/

  fonts:
    - family: GurbaniAkhar
      fonts:
        - asset: assets/fonts/GurbaniAkhar.ttf
    - family: Punjabi
      fonts:
        - asset: assets/fonts/AnmolLipi.ttf